### ISSUE TITLE
ModuleNotFoundError: No module named 'loguru'

### ISSUE THREAD

**Issue by RcTomcat1** [opencv-ai/oak-model-samples#10]
Hi,

basically every sample i tried gives me the following error:
lightweight_openpose\modelplace_api\utils.py", line 5, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

I am currently running a windows 10 system with an oak-d camera connected to it.
I followed the install instructions and ran the setup.py

Checking via pip loguru should be installed:
pip install loguru
Requirement already satisfied: loguru in c:\program files\python39\lib\site-packages (0.5.1)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\program files\python39\lib\site-packages (from loguru) (1.0.3)
Requirement already satisfied: colorama>=0.3.4 in c:\program files\python39\lib\site-packages (from loguru) (0.4.4)

What am i missing?

**Comment by PVSemk** [comment]
Hello!
Do you have a single version of python3 installed on your device? If not, I'd suggest to check that you setup and launch the package with the same interpreter (it seems like 'pip' refers to python3.9). 
Also you may try to setup a virtual environment to install and test packages inside it to avoid messing up with the system interpreter (see https://docs.python.org/3/library/venv.html )

**Comment by RcTomcat1** [comment]
Thanks. I justs tried with a virtual environment and am running into the same issue.
Module error after module error unless i manually download, build and copy those modules into the folder of the sample i am trying to run.

**Comment by RcTomcat1** [comment]
Ok. I gave up on windows and switched to a pi.
Got different issues now....
```
(opencv) pi@raspberrypi:~/depthai/oak-model-samples/openpose $ python3 main.py -vid ./demo.mp4
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    main()
  File "main.py", line 13, in main
    inference(model_cls, root_model_path, visualization)
  File "/home/pi/depthai/opencv/lib/python3.7/site-packages/oak_inference_utils/inference.py", line 63, in inference
    model.model_load(openvino_version=openvino_version, use_camera=args.camera)
  File "/home/pi/depthai/opencv/lib/python3.7/site-packages/oak_inference_utils/base_model.py", line 93, in model_load
    self.create_pipeline(model_blob)
  File "/home/pi/depthai/opencv/lib/python3.7/site-packages/oak_inference_utils/base_model.py", line 79, in create_pipeline
    self.model_blob.setBlobPath(model_blob)
RuntimeError: BlobReader error: File does not seem to be a supported neural network blob

```

**Comment by PVSemk** [comment]
Could you reproduce steps you did to launch samples on Windows?
As for issue on a pi, it seems like a git-lfs connected trouble. Please, see #7 for details

**Comment by RcTomcat1** [comment]
Thank you, the git lfs pull did the trick :)

I can't seem to figure out what is wrong with the windows install. Guess i messed it up somewhere along the way.
