### ISSUE TITLE
Windows installation commands for OpenPose

### ISSUE THREAD

**Issue by AdriBee** [opencv-ai/oak-model-samples#4]
This is related with OpenPose example, but I think it will affect the other examples too. 

################
Set up a package:

2.1 python3 setup.py bdist_wheel && rm -R build/ *.egg-info

2.2 pip3 install dist/*.whl -f https://artifacts.luxonis.com/artifactory/luxonis-python-snapshot-local/depthai/ && rm -R dist/

################

This commands do not work on Windows.
"rm" needs to be replaced by "del"
Also, "python3" does not work on Windows, it should be "python".
I am having problems translating this command to Windows CMD... Unable to install the dist and to execute those commands.
Could you please provide an installation guide for Windows?

Thanks!

PD: I am a newbie.

**Comment by PVSemk** [comment]
Hi, thanks for your interest!
We're currently testing the Windows installation. 
We'll merge it ASAP

**Comment by lxdv** [comment]
Windows installation guide is added - https://github.com/opencv-ai/oak-model-samples/blob/main/docs/INSTALLATION_USAGE_GUIDE.md#installation

Thank you for your feedback. Let us know if you have any questions.
