### ISSUE TITLE
Blob files not cloning as expected

### ISSUE THREAD

**Issue by AndrewBarfield** [opencv-ai/oak-model-samples#7]
Ubuntu 20.10
Python 3.8
DepthAI 0.0.2.1+87247bfb645027a30c68191d88fe1b69b70e39ac
Git 2.27.0

I don't know if this is by design or a problem, but blob files aren't cloning as expected.

I cloned this repo using:

```
git clone https://github.com/opencv-ai/oak-model-samples.git
```

But all "checkpoint/*blob" files are actually text files similar to:

```
version https://git-lfs.github.com/spec/v1
oid sha256:ae7da3959157fde405376d9aa53147c4130c475119f012f33e5f22dac880adb4
size 1341888
```

To get the samples to work I have to return to GitHub and browse to a "checkpoint" folder like "https://github.com/opencv-ai/oak-model-samples/tree/main/facial_landmarks_35_adas/checkpoint", select a blob file, and then click "view raw" to download it to the respective checkpoint folder.

**Comment by PVSemk** [comment]
Hello, thank you for your interest!

We store all blob files under git-lfs. I believe you should install it. In your case you can use the following command:
`sudo apt-get install git-lfs`
Then change working directory to the repo's root and launch:
`git lfs install`
`git lfs pull`
All blob files will be downloaded.
Please, tell us if something doesn't work

**Comment by AndrewBarfield** [comment]
This works like a charm! Closing the issue.
