### ISSUE TITLE
ModuleNotFoundError: No module named 'modelplace_api'

### ISSUE THREAD

**Issue by Pugnacioius** [opencv-ai/oak-model-samples#8]
Try to run yolov4_tiny as suggested:  python3 main.py -cam -vid

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from modelplace_api.visualization import draw_detections_one_frame
ModuleNotFoundError: No module named 'modelplace_api'

**Comment by AndrewBarfield** [comment]
You need to clone the modelplace-api repo and build/install it. Worked for me.

**Comment by PVSemk** [comment]
Hello, thanks for your feedback.
Please, make sure that you setup the model as suggested in [installation guide](https://github.com/opencv-ai/oak-model-samples/blob/main/docs/INSTALLATION_USAGE_GUIDE.md). `modelplace_api` package should be installed along with other required modules automatically.

**Comment by PVSemk** [comment]
Closed due to inactivity.
Feel free to re-open if you have any related questions
