### ISSUE TITLE
Is OAK-1 capable of providing depth data?

### ISSUE THREAD

**Issue by franva** [opencv-ai/oak-model-samples#9]
Hi there,

I have read through both OAK-1 and OAK-D. 

It seems that they both are able to provide depth data.

Could you please confirm this?

**Comment by AndrewBarfield** [comment]
Only OAK-D can provide depth data. It has 3 total cameras: 1 RGB and two stereo cameras.

OAK-1 has only the RGB camera.

**Comment by franva** [comment]
Hi @AndrewBarfield   thanks for your reply.

if the OAK-1 does not provide depth data, why it states the depth here?
![image](https://user-images.githubusercontent.com/5151146/126039871-1fc221a6-4833-45eb-8034-5878653b439d.png)
Here is the URL: https://store.opencv.ai/products/oak-1

**Comment by AndrewBarfield** [comment]
I've sent a message to store.opencv.ai about the issue.

I've also invited them to respond here.

**Comment by AndrewBarfield** [comment]
OpenCV responded:

"Hi Andrew,

Thanks for answering it on GitHub.

We appreciate your pro-activeness and agree with the answer provided as OAK-1 is not capable of providing Depth data.

We have made the necessary changes to our Store Website’s product description accordingly.

Thanks once again for highlighting! 😊

--

Regards,
OpenCV Team"

**Comment by AbbasMolvi** [comment]
> 
> 
> Hi there,
> 
> I have read through both OAK-1 and OAK-D.
> 
> It seems that they both are able to provide depth data.
> 
> Could you please confirm this?

Thanks for highlighting it.

We have corrected the OAK-1 description at the store now - https://store.opencv.ai/products/oak-1

**Comment by franva** [comment]
hi @AndrewBarfield  where did you ask OpenCV for the question?

I thought this is the official github for the Oak camera from Open CV.

**Comment by AndrewBarfield** [comment]
@franva,

I clicked on "Get in touch" on https://store.opencv.ai/products/oak-1.

Direct link: https://store.opencv.ai/pages/get-in-touch
